- hosts: target
  roles:
    - ansible

- hosts: target
  vars:
    workdir: ~/wks
  tasks:
    - name: make wks directory
      file:
        path: "{{ workdir }}"
        state: directory

    - name: check out cloud-init
      git:
        repo: http://git.tateishi/git/tadatoshi/cloud-init.git
        dest: ~/wks/cloud-init

    - git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop:
        - repo: https://github.com/tateishi/playbook-work.git
          dest: "{{ workdir }}/playbook-work"
